### ISSUE TITLE
Is the license MIT?

### ISSUE THREAD

**Issue by zeritonius** [cerebralideas/todomvc-client-reasonreact#29]
I don't see an explicit license for the repository, but I see "license": "MIT", in the package.json file. Does the MIT license apply to the whole repository, please?

Thank you.

**Comment by cerebrl** [comment]
Hello @zeritonius, thanks for reaching out. Yes, this project is MIT licensed. I'll try to find some time to explicitly put a license file in the repo.

Please be aware that this project is really old and unmaintained, but you're welcome to use it. May I ask why you are interested?

**Comment by zeritonius** [comment]
**>>> Yes, this project is MIT licensed.**
Thank you for clarifying this.

**>>> I'll try to find some time to explicitly put a license file in the repo.**
Actually, there are other projects of yours without an explicit license, and I was wondering if they are MIT as well.

According to this link, it will take less than 30 seconds to add an explicit license
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**>>> Please be aware that this project is really old and unmaintained, but you're welcome to use it.**
Thank you for letting me know.

**>>> May I ask why you are interested?**
I'm interested in MIT in general, and in ToDo projects in particular. I'm a collector.
I love MIT because it explicitly gives me permission to use also the documentation, which many other licenses don't, particulary Apache and BSD. MIT it's not copyleft, which is a big plus for me.

I got interested in MVC due to https://todomvc.com/ In time, I plan to create a video for each implementation I understand. One thing that wasn't obvious for me when I saw some implementations was that the CSS was responsible to the look and that the logic was way more easier for me to understand with the CSS disabled.

I always ask if I'm interested in a repository and I don't see an explicit license.
Sometimes they add it:
https://github.com/denoland/manual/issues/58
while others they don't answer at all

If I don't see a license then I can't use that repository and I skip it. If a repository matches a nice license (like MIT) and it's on a domain of interes to me (ToDoMVC), I add it to my list for future "to-learn-from" topics.

You didn't ask, but I'll do a trace of how I found you.
I asked a question on another repository and someone answered it. That person has 1.5k followers (me included) and following just one person. Which, of course, made me courious who was the only person followed. :)

**Comment by cerebrl** [comment]
License added.
